<?php

/**
 * @file
 * Custom Commerce pane example
 *
 * This file impliments a few basic commerce panes to show as an example.
 */

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function commerce_pane_example_commerce_checkout_pane_info() {
  $checkout_panes = array();

  $checkout_panes['commerce_pane_example_form_pane'] = array(
    'title' => t('Example Form Pane'),
    'page' => 'checkout',
    'locked' => TRUE,
    'base' => 'commerce_pane_example_form_pane',
    'weight' => 1,
  );

  $checkout_panes['commerce_pane_example_markup_pane'] = array(
    'title' => t('Example Markup Pane'),
    'page' => 'checkout',
    'locked' => TRUE,
    'base' => 'commerce_pane_example_markup_pane',
    'weight' => 2,
  );

  return $checkout_panes;
}

function commerce_pane_example_form_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  $pane_form = array();

  $pane_form['username'] = array(
    '#type' => 'textfield',
    '#title' => 'Username',
    '#description' => 'Enter your Drupal.org username',
    '#required' => TRUE,
  );

  return $pane_form;
}

function commerce_pane_example_form_pane_checkout_form_validate($form, &$form_state, $checkout_pane, $order) {
  $username = $form_state['values']['commerce_pane_example_form_pane']['username'];
  if(strlen($username) < 2) {
    form_set_error('username', 'Your username is too short, dont be faking us out!');
  }
}

function commerce_pane_example_form_pane_checkout_form_submit($form, &$form_state, $checkout_pane, $order) {
  //form processing goes here
  //@todo add good example code here
}

function commerce_pane_example_markup_pane_checkout_form($form, &$form_state, $checkout_pane, $order) {
  $pane_form = array();

  $pane_form['promotion'] = array(
    '#markup' => 'This is custom text that we can place anywhere in our checkout form!',
  );

  return $pane_form;
}